### ISSUE TITLE
Duplicate files

### ISSUE THREAD

**Issue by fariasmateuss** [guilhermerodz/input-otp#16]
I found files with duplicate logic to utility to merge class names in:
https://github.com/guilhermerodz/input-otp/blob/de9d59eb69520fecd9b19d545c999a2c6689b415/apps/website/src/lib/utils.ts#L4

https://github.com/guilhermerodz/input-otp/blob/de9d59eb69520fecd9b19d545c999a2c6689b415/apps/website/src/lib/utils/cn.tsx#L6

This is intentional?

**Comment by guilhermerodz** [comment]
Thanks! Solved by f52614dc52e073005fd05cc95acf03f4805edb0d

**Comment by fariasmateuss** [comment]
Hi @guilhermerodz, I prepared a PR #18 for this, but too late. LOL
