### ISSUE TITLE
[BUG] Save in 1Password Button Overlaps Input

### ISSUE THREAD

**Issue by jenewland1999** [guilhermerodz/input-otp#30]
## Expected Behavior

Either the 1Password button save button is disabled or the CSS is adjusted to ensure it does not overlap the actual input's text

## Current Behavior

The Save in 1Password Button overlaps the final digit in the OTP input obscuring the entered digit either partially or entirely.

## Possible Solution

You can read a bit more about handling or disabling the 1Password integration in [1Password's docs](https://developer.1password.com/docs/web/add-1password-button-website/)

## Steps to Reproduce

1. Install 1Password Extension in your favourite browser of choice
2. Visit a page where the OTPInput is being used (e.g. https://ui.shadcn.com/docs/components/input-otp or https://input-otp.rodz.dev/)
3. Focus the input
4. Ta-da! You now see the Save in 1Password Button overlapping the input 🎉

## Context (Environment)

- Using Chrome 122 on macOS Sonoma 14.4
- Also tested on Safari 17.4 and Firefox 123
- Would likely also affect other password managers like LastPass and Dashlane though I've not tested this

## Detailed Description

n/a

## Possible Implementation

n/a

**Comment by jenewland1999** [comment]
Just seen that you made 8f4e92fa777dc7282fcfbe4b81dbbf632038fb31 a few hours ago so, I think my issue may already be redundant. That timing tho 😅

**Comment by guilhermerodz** [comment]
yep that's solved in the next release!

**Comment by guilhermerodz** [comment]
solved by 8f4e92f all the way until 5ee7e6e5d003b2d5a726dcfc1584934dc6ec5d69
