### ISSUE TITLE
[BUG] Backspace doesn't work for the first field after starting to delete in the middle

### ISSUE THREAD

**Issue by blvdmitry** [guilhermerodz/input-otp#40]
## Expected Behavior

Input can be cleared completely

## Current Behavior

Input keeps the last character filled, navigating to the next item and back fixes this behavior

## Steps to Reproduce

https://github.com/guilhermerodz/input-otp/assets/887379/2e7dbda9-0dfc-4c3f-8dcb-9a13a0083fe1

I'm using backspace on the video to delete the characters

## Context (Environment)

Just noticed that this happens on the landing page

**Comment by guilhermerodz** [comment]
hi @blvdmitry thank you so much for reporting this.

that is now solved on b02cee8f95aa92906d6947ec5bf66541b9e66134

however, the test pipeline is broken (I couldn't tell why) and will publish a new 1.2.4 version on NPM as soon as it's fixed.

**Comment by guilhermerodz** [comment]
solved now on 1.2.4, please update latest
