### ISSUE TITLE
[BUG]:  Form elements do not have associated labels - Accessibility issue on documentation

### ISSUE THREAD

**Issue by withden** [guilhermerodz/input-otp#41]
## Current Behavior
![Screenshot from 2024-04-08 08-32-23](https://github.com/guilhermerodz/input-otp/assets/57515871/88ee96be-cb01-4624-98bb-f8b0b844cd74)

## Possible Solution
I'm working on it, I will probably create a PR request for it.

## Steps to Reproduce

1. Open the dev console (chrome or any browser).
2. Do the lighthouse analysis

**Comment by guilhermerodz** [comment]
hi @withden that is not a bug with the library, it's definitely an accessibility issue on the website as I haven't created an <label htmlFor> for the input in the center of the landing page. but definitely not an issue on the library itself.

**Comment by guilhermerodz** [comment]
sure thing @withden make sure to keep the same current landing page appearance (spacing, etc). so no changes visually, while still addressing the missing `<label htmlFor>` issue. thank you so much!
