### ISSUE TITLE
I want to go to the particular box edit!

### ISSUE THREAD

**Issue by broisnischal** [guilhermerodz/input-otp#43]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by guilhermerodz** [comment]
hi @broisnischal that would be a nice feature!

however, I believe that's not possible when it comes to rendering a singular native input

check out https://github.com/guilhermerodz/input-otp/issues/32
