### ISSUE TITLE
Do something after all required fields where inserted

### ISSUE THREAD

**Issue by ImamJanjua** [guilhermerodz/input-otp#50]
Hi, how can i perform some action after the user has filled all the required input fields. But like without a button to submit?

**Comment by NicolasCassunde** [comment]
You can use OnComplete to do it

`<InputOTP onComplete={(e: string) => onComplete(e)} maxLength={6}>
        <InputOTPGroup>
          <InputOTPSlot index={0} />
          <InputOTPSlot index={1} />
          <InputOTPSlot index={2} />
        </InputOTPGroup>
        <InputOTPSeparator />
        <InputOTPGroup>
          <InputOTPSlot index={3} />
          <InputOTPSlot index={4} />
          <InputOTPSlot index={5} />
        </InputOTPGroup>
      </InputOTP>`
