### ISSUE TITLE
Add a MIT license for this project

### ISSUE THREAD

**Issue by OscarHagman** [guilhermerodz/input-otp#57]
Sorry in advance if this belongs somewhere else other than feature request, let me know if you want me to move it elsewhere.

**Is your feature request related to a problem? Please describe.**
Yes, the problem is that I can't legally use this component because it doesn't have a license that explicitly says that it's free to be used, so the default copyright laws are applied. This means all rights are reserved to the author and I can't legally copy, distribute, or create derivative work from the code. This also applies to the npm package, even tho it's publicly available the default copyright laws still applies.

**Describe the solution you'd like**
Add a license that clearly describes how a individual can use this code (preferably a MIT licence)

**Comment by guilhermerodz** [comment]
hey! sorry for the delay. sure, it deserves a license. I'll add it whenever possible

**Comment by guilhermerodz** [comment]
https://github.com/guilhermerodz/input-otp/commit/6d74289761f3c24fbb2ab907aff481e1038b7e06
