### ISSUE TITLE
Automatic OTP code retrieval from transport?

### ISSUE THREAD

**Issue by shaun-fitzgibbon** [guilhermerodz/input-otp#58]
Automatic OTP code retrieval from transport?

Does this mean you have to click the sms when it appears at the bottom on your mobile to enter it into your OTP input or that when you receive the sms it will retrieve the pin automatically and enter it in your input with out user interaction ?

Im looking get the functionality that it will retrieve the code automatically like some sites do so the user does not need to do anything on mobile

**Comment by shaun-fitzgibbon** [comment]
my understanding from the wording here is it should work without user interaction but I cannot get it to do this 
is there some setup I need to configure ?

**Comment by guilhermerodz** [comment]
@shaun-fitzgibbon you can actually do this by applying the HTML property `autocomplete="one-time-code"`, but you can also implement the [WebOTP API](https://web.dev/articles/sms-otp-form#use_the_webotp_api)

Perhaps this could turn into an official feature of `input-otp` in the future.

**Comment by shaun-fitzgibbon** [comment]
Thanks for the response @guilhermerodz much appreciated.
I was under the impression that by default the  autocomplete="one-time-code" is already set using input-otp ?

![Screen Shot 2024-08-04 at 14 06 30 PM](https://github.com/user-attachments/assets/564fb980-d10c-4ca4-b750-0625cbf26548)

**Comment by guilhermerodz** [comment]
> Thanks for the response @guilhermerodz much appreciated. I was under the impression that by default the autocomplete="one-time-code" is already set using input-otp ?
> 
> ![Screen Shot 2024-08-04 at 14 06 30 PM](https://private-user-images.githubusercontent.com/5940631/354900418-564fb980-d10c-4ca4-b750-0625cbf26548.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMyNDUyMTIsIm5iZiI6MTcyMzI0NDkxMiwicGF0aCI6Ii81OTQwNjMxLzM1NDkwMDQxOC01NjRmYjk4MC1kMTBjLTRjYTQtYjc1MC0wNjI1Y2JmMjY1NDgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MDlUMjMwODMyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTI1YjQ0NzgwNWQ1ZDc5YTdmNzk5Yzc3NDgwNGYxNTFmZTg1YWQ1M2ZhOWEzNWJmNzdlMzAxMzFkMWE5OWFlZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.mEz87EkXQuFpShhUdQ_lyI1xPcCJ3e1DgfoUIUn5zQ4)

Its default is `autocomplete='one-time-code'` indeed. However, I'm not sure what behavior you are trying to achieve. If you want to work with WebOTP API, that's not included in `input-otp` by default.

**Comment by timblackwell** [comment]
Apologies for bumping an old thread, I just thought I'd share my findings here as it might help someone searching in the future.

Automatic OTP code retrieval works on iOS with SMS and Email with `autoComplete='one-time-code'`.
On Android you need to use [WebOTP API](https://web.dev/articles/sms-otp-form#use_the_webotp_api) as mentioned above but also it only works for SMS currently.
