### ISSUE TITLE
[BUG] autoFocus not triggering keyboard on iOS devices

### ISSUE THREAD

**Issue by MorganMeirFitussi** [guilhermerodz/input-otp#61]
## Expected Behavior
When the OTPInput component is rendered with `autoFocus`, the first slot should be focused, and the keyboard should automatically appear on iOS devices.

## Current Behavior
When using the OTPInput component with the autoFocus prop set to true, the first slot is correctly focused on iOS devices (both web and native), but the keyboard does not automatically appear. Users must tap on the focused slot to make the keyboard appear.

## Steps to Reproduce
1. Create a new project using the input-otp library
2. Implement the OTPInput component with the autoFocus prop set to true
3. Run the project on an iOS device (either in a web browser or as a native app)
4. Observe the behavior when the OTPInput component is rendered

I've created a [CodeSandbox](https://codesandbox.io/p/sandbox/modest-scooby-2qps55?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clztl0o2700063b6n74vpo4y4%2522%252C%2522sizes%2522%253A%255B100%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clztl0o2700023b6nbo6dz616%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clztl0o2700033b6nvyo79n4q%2522%257D%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clztl0o2700053b6ncxpkf729%2522%257D%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clztl0o2700023b6nbo6dz616%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clztl0o2700013b6ngy6atcwl%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clztl0o2700023b6nbo6dz616%2522%252C%2522activeTabId%2522%253A%2522clztl0o2700013b6ngy6atcwl%2522%257D%252C%2522clztl0o2700053b6ncxpkf729%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clztl0o2700043b6n305cizj0%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%257D%255D%252C%2522id%2522%253A%2522clztl0o2700053b6ncxpkf729%2522%252C%2522activeTabId%2522%253A%2522clztl0o2700043b6n305cizj0%2522%257D%252C%2522clztl0o2700033b6nvyo79n4q%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clztl0o2700033b6nvyo79n4q%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D) to demonstrate this issue

**Comment by ETOPS7** [comment]
I also noticed this problem today on iOS devices

**Comment by guilhermerodz** [comment]
How awkward. No idea why the keyboard wouldn't be triggering...

**Comment by guilhermerodz** [comment]
Hey @MorganMeirFitussi I just found out that won't work with iOS. It won't work with a normal `<input />`, too. See this is the only workaround and it's not pretty https://gist.github.com/cathyxz/73739c1bdea7d7011abb236541dc9aaa?permalink_comment_id=4412959#gistcomment-4412959

Even tho there's a workaround available for that, it shouldn't be responsibility of `input-otp`'s but more of a general knowledge on iOS inputs.
