### ISSUE TITLE
[BUG] Adding CSP security protocols

### ISSUE THREAD

**Issue by petranlaurentiu** [guilhermerodz/input-otp#63]
Issue tracker is **ONLY** used for reporting bugs. New features should be discussed on our slack channel. Please use [stackoverflow](https://stackoverflow.com) for supporting issues.

## Expected Behavior

I am unable to pass my numbers in the input-otp componet when I remove 'unsafe-eval' from my cspHeaders.
If I add 'unsafe-eval', then it works fine. 
## Steps to Reproduce

1.
2.
3.
4.

**Comment by guilhermerodz** [comment]
Closing only temporarily while I wait for a demo
