### ISSUE TITLE
[FEATURE_REQUEST] inputType = "password"

### ISSUE THREAD

**Issue by deleonjuan** [guilhermerodz/input-otp#69]
**Is your feature request related to a problem? Please describe.**
I want to use this as a password input and I would like to see asterisks(*) on screen instead of the actual values

**Describe the solution you'd like**
add "password" to the posible types so it render something like asterisks or little dots.

now: 123-123
with type="password": ***-***

**Comment by guilhermerodz** [comment]
Well, you can render * or whatever you want in case the inputType is password. It doesn't need to be the actual character. I am unsure this should be a feature though
