### ISSUE TITLE
[BUG] onBlur fires early when autoFocus is enabled

### ISSUE THREAD

**Issue by andrew-pledge-io** [guilhermerodz/input-otp#72]
## Expected Behavior
`onBlur` should only be fired when focus leaves the OTPInput component.

## Current Behavior
`onBlur` is fired when OTPInput component mounts when `autoFocus` is true.

## Steps to Reproduce

Example:

https://codesandbox.io/p/sandbox/lw5m99

## Context (Environment)

Calling `onBlur` early causes issues when used with e.g. RHF as the input becomes "touched", triggering validation early.

**Comment by guilhermerodz** [comment]
Fixed as of 1.4.0
