### ISSUE TITLE
[wierd]: Clicking any slot just clicks the last one

### ISSUE THREAD

**Issue by jacob-leger** [guilhermerodz/input-otp#76]
# What Is The Problem?

When using the Input OTP component, I can navigate using the arrow keys.

<details><summary>Uses of Each Arrow Key</summary>
<p>

- Up: Navigate to the first slot
- Down: Navigate to the last (inputtable) slot
- Left: Move one slot to the left
- Right: Move one slot to the right

</p>
</details>

**However, I cannot navigate it with my mouse. If a slot is clicked, it will *always* select the last selectable one.**

## How Was This Discovered

I was browsing [the ShadCN/UI docs](https://ui.shadcn.com/docs) when I saw the [Input OTP component](https://ui.shadcn.com/docs/components/input-otp). After playing around with it, I noticed this bug. I created an issue in the ShadCN/UI repo, but was told it was a problem/decision with the base component's repo. The original issue is posted [here](https://github.com/shadcn-ui/ui/issues/4046#issuecomment-2304836890). 

## An Additional Thought

Additionally, I can not even use the arrow keys to select an empty space (not including the one following the last inputted digit). For all I know, this may be intentional, and I'd agree with the decision.

### How to reproduce

1. Access the component (either on your own machine or on [the website](https://input-otp.rodz.dev/))
2. Type any random numbers. E.g., 1234
3. Navigate Using The Arrow Keys
4. Try to click on a cell (not including the last filled), and it will just select the last cell, no matter what 😭

### System Info

```
Chrome Version 126.0.6478.114 (Official Build, 64 Bit) on a Windows 11 PC.
```

**Comment by guilhermerodz** [comment]
Hi, this is not possible with the current implementation of `input-otp`. See https://github.com/guilhermerodz/input-otp/issues/32
