### ISSUE TITLE
Hidden input width

### ISSUE THREAD

**Issue by pasqualevitiello** [guilhermerodz/input-otp#78]
Not sure if it's intentional - the hidden input width is 100% + 40px, and it may be cause of overflowing issues. 

<img width="1596" alt="Screenshot 2024-11-26 at 14 14 54" src="https://github.com/user-attachments/assets/fbd79d29-e19f-45aa-82a2-37d643af3477">

**Comment by gnllucena** [comment]
it's causing problems with embla-carousel for me, how can I override this width?

**Comment by gnllucena** [comment]
it's written in the readme:

pushPasswordManagerStrategy="none"

**Comment by pasqualevitiello** [comment]
Oh, I totally missed that!
